gcp:
  config:
    file: gcp-storage-file.json
  project:
    id: sharepic-377714
  bucket:
    id: sharepic_files

file:
  upload-dir: C:/Users/002LSO744/Pictures

logging:
  level:
    org.springframework: ERROR
    com.sharepic: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
    name: app.log
    
